databases:
  - name: itsm-db
    databaseName: itsm_h0eb
    user: itsm_user
    plan: free
    region: oregon

services:
  - type: web
    name: itsm_api
    runtime: ruby
    plan: free
    buildCommand: |
      bundle install && rails assets:precompile
    startCommand: |
      bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: itsm-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
    autoDeploy: true
