# Exported from Render on 2025-07-28T04:52:59Z
databases:
- name: itsm-production-db
  databaseName: itsm_production_db_plyf
  user: itsm_production_db_plyf_user
  plan: basic-256mb
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
  diskSizeGB: 1
version: "1"
