version: "1"

databases:
  - name: itsm-postgres
    databaseName: itsm_production
    user: itsm_user
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"

services:
  - type: web
    name: itsm-api
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: itsm-postgres
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: RAILS_MAX_THREADS
        value: "5"
    healthCheckPath: /health
    autoDeploy: true