databases:
  - name: ITSM_API
    databaseName: ITSM_DB
    user: ITSM_USER
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0 --verbose"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false  
      - key: DATABASE_URL
        fromDatabase:
          name: ITSM_API
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2 