default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("ITSM_API_DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("ITSM_API_DATABASE_PASSWORD") { 'postgres' } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: itsm_api_development

test:
  <<: *default
  database: itsm_api_test

production:
  <<: *default
  database: itsm_api_production
  username: <%= ENV.fetch("ITSM_API_DATABASE_USERNAME") { 'itsm_api' } %>
  password: <%= ENV.fetch("ITSM_API_DATABASE_PASSWORD") %>
