default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: itsm_development

test:
  <<: *default
  database: itsm_test

production:
  <<: *default
  database: itsm_production_db_plyf
  sslmode: require
