default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] || 5432 %>
  variables:
    lock_timeout: "5s"

development:
  <<: *default
  database: itsm_api_development

test:
  <<: *default
  database: itsm_api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>?sslmode=require
  variables:
    lock_timeout: "5s"
