default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  sslmode: require
  connect_timeout: 15
  keepalives_timeout: 10
  # Prevent connection leaks and improve behavior in containerized environments
  reaping_frequency: 10
  checkout_timeout: 10

development:
  <<: *default
  database: itsm_development
  username: <%= ENV.fetch("DB_USERNAME", "tendai") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Mybreak28#") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

test:
  <<: *default
  database: itsm_test
  username: <%= ENV.fetch("DB_USERNAME", "tendai") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Mybreak28#") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

production:
  # Use DATABASE_URL as the source of truth
  url: <%= ENV["DATABASE_URL"] %>
  # Inherit defaults for any non-URL settings
  <<: *default
  # Disable prepared statements to avoid issues with Render's PgBouncer
  prepared_statements: false
  # Prevent long-running queries
  statement_timeout: 30000
  # Increase pool size if needed (adjust based on RAILS_MAX_THREADS)
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>
  # Optional: Set application name for easier debugging in PostgreSQL logs
  # application_name: itsm-production
