default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  sslmode: require # Critical for Render's upgraded DB
  connect_timeout: 15
  keepalives_timeout: 10

development:
  <<: *default
  database: itsm_development
  username: <%= ENV.fetch("DB_USERNAME", "tendai") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Mybreak28#") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

test:
  <<: *default
  database: itsm_test
  username: <%= ENV.fetch("DB_USERNAME", "tendai") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Mybreak28#") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %> # Contains host, user, pass, sslmode
  # Override any defaults if needed
  prepared_statements: false # Recommended on Render due to PgBouncer
  statement_timeout: 30000
